name: API
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - 'packages/db/**'
      - '.github/workflows/api.yml'
  pull_request:
    paths:
      - 'packages/api/**'
      - 'packages/db/**'
      - '.github/workflows/api.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run build --workspace packages/api
      - run: npm test --workspace packages/api

  deploy-staging:
    name: Deploy Staging API
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Publish api worker
        # workaround for https://github.com/cloudflare/wrangler-action/issues/59 to use node 16
        uses: web3-storage/wrangler-action@node16
        env:
          SENTRY_TOKEN: ${{ secrets.STAGING_SENTRY_TOKEN}}
          SENTRY_PROJECT: ${{ secrets.STAGING_SENTRY_PROJECT}}
          SENTRY_UPLOAD: ${{ secrets.STAGING_SENTRY_UPLOAD}}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
          environment: 'staging'
      - name: Test upload to staging
        run: |
          npm run build -w packages/client
          echo "$(date --utc --iso-8601=seconds) web3.storage upload test" > ./upload-test-small
          ./packages/w3/bin.js put ./upload-test-small --api https://api-staging.web3.storage --token ${{ secrets.STAGING_WEB3_TOKEN }}
